apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        env:
        {{ if eq .Values.application.env "prod" }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sentry-dsn
        {{ end }}

        {{ if eq .Values.postgresql.enabled true }}
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        {{ else }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-url
        {{ end }}
        {{ if eq .Values.redis.enabled true }}
        - name: REDIS_HOST
          value: {{ template "webping.redis.fullname" . }}
        - name: REDIS_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ template "webping.redis.fullname" . }}
              key: redis-password
        {{ else }}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: redis-url
        {{ end }}
        - name: WEBPING_ENV
          value:  {{ .Values.application.env }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}-worker
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.workerReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - ./bin/run_celery.sh
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        env:
        {{ if eq .Values.application.env "prod" }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sentry-dsn
        {{ end }}
        {{ if eq .Values.postgresql.enabled true }}
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        {{ else }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-url
        {{ end }}
        {{ if eq .Values.redis.enabled true }}
        - name: REDIS_HOST
          value: {{ template "webping.redis.fullname" . }}
        - name: REDIS_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ template "webping.redis.fullname" . }}
              key: redis-password
        {{ else }}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: redis-url
        {{ end }}
        - name: WEBPING_ENV
          value:  {{ .Values.application.env }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}-beat
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.workerReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - ./bin/run_celery_beat.sh
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        env:
        {{ if eq .Values.application.env "prod" }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sentry-dsn
        {{ end }}
        {{ if eq .Values.postgresql.enabled true }}
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        {{ else }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-url
        {{ end }}
        {{ if eq .Values.redis.enabled true }}
        - name: REDIS_HOST
          value: {{ template "webping.redis.fullname" . }}
        - name: REDIS_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ template "webping.redis.fullname" . }}
              key: redis-password
        {{ else }}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: redis-url
        {{ end }}
        - name: WEBPING_ENV
          value:  {{ .Values.application.env }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
