# Generated by Django 2.2.6 on 2019-12-27 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='web_source_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('title', models.TextField()),
                ('texts', models.TextField()),
                ('imageScreenShot', models.TextField()),
                ('pageHeight', models.IntegerField()),
                ('status', models.TextField()),
                ('original_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('time_scan', models.FloatField()),
                ('limit_change', models.FloatField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='web_sub_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.CharField(max_length=200)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_url', to='app.web_source_code')),
            ],
        ),
        migrations.AddField(
            model_name='web_source_code',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_source', to='app.Website'),
        ),
        migrations.CreateModel(
            name='web_resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('js_url', models.TextField()),
                ('css_url', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_resource', to='app.web_source_code')),
            ],
        ),
        migrations.CreateModel(
            name='DataCrawl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('source_code', models.TextField()),
                ('texts', models.TextField()),
                ('directions', models.TextField()),
                ('imageScreenShot', models.TextField()),
                ('status', models.TextField()),
                ('pageHeight', models.IntegerField()),
                ('original_data', models.BooleanField(default=False)),
                ('timeCrawl', models.DateTimeField(default=django.utils.timezone.now)),
                ('uri_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Website')),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similar_percentages', models.FloatField(default=1.0)),
                ('data_old', models.TextField()),
                ('source_old', models.TextField()),
                ('source_new', models.TextField()),
                ('source_compare', models.TextField()),
                ('source_changes', models.TextField()),
                ('text_old', models.TextField()),
                ('text_new', models.TextField()),
                ('text_compare', models.TextField()),
                ('text_changes', models.TextField()),
                ('directions_old', models.TextField()),
                ('directions_new', models.TextField()),
                ('directions_compare', models.TextField()),
                ('directions_changes', models.TextField()),
                ('image_changes', models.TextField()),
                ('data_crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataCrawl')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeAddress', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('imageScreenShot', models.TextField()),
                ('uri_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Website')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('typeAddress', 'uri_id', 'address')},
            },
        ),
    ]
