# Generated by Django 3.0.4 on 2020-09-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200909_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('district', 'city')},
        ),
    ]
