# Generated by Django 3.0.4 on 2020-09-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200909_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cost',
            new_name='price',
        ),
    ]
