# Generated by Django 3.0.4 on 2020-09-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200910_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
